<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add feedback' => 'Додати відгук',
    'Date' => 'Дата',
    'Feedback' => 'Відгук',
    'Feedbacks' => 'Відгуки',
    'Form errors. {open_link}Back to form.{close_link}' => 'Форма заповнена з помилкамми. {open_link}Перейти до форми.{close_link}',
    'Guestbook' => 'Гостьова книга',
    'Incorrect Code' => 'Невірно введений код',
    'Invalid email' => 'Некоректний email',
    'Invalid url' => 'Некоректний url',
    'Name' => 'Ім\'я',
    'Preview' => 'Попередній перегляд',
    'Send' => 'Відправити',
    'Tags:' => 'Теги:',
    'Tags closing/opening error.' => 'Не вірно закриті/відкриті теги.',
    'This field is required' => 'Не заповнене поле',
    'You have used forbidden tags. Whitelist: {tags}.' => 'Використані заборонені теги. Список дозволених: {tags}',
    '{name}, your feedback has been sent.' => '{name}, ваш відгук відправлено.',
];
